//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vApus.Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vApus.Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Authors&gt;
        ///	&lt;Author name=&quot;Dieter Vandroemme&quot; email=&quot;dieter@sizingservers.be, dieter.vandroemme@gmail.com&quot; period=&quot;2007-Present&quot; linkedInID=&quot;dietervandroemme&quot; /&gt;
        ///	&lt;Author name=&quot;Glenn Desmadryl&quot; email=&quot;glenn@sizingservers.be&quot; period=&quot;2009-Present&quot; linkedInID=&quot;glenndesmadryl&quot; /&gt;
        ///	&lt;Author name=&quot;Philip Dubois&quot; email=&quot;philip@sizingservers.be&quot; period=&quot;2012-Present&quot; linkedInID=&quot;philipdubois&quot; /&gt;
        ///	&lt;Author name=&quot;Liz van Dijk&quot; email=&quot;liz@sizingservers.be&quot; period=&quot;2011-2012&quot; linkedInID=&quot;lizvandijk&quot; /&gt;
        ///&lt;/Authors&gt;.
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap delete16x16 {
            get {
                object obj = ResourceManager.GetObject("delete16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Dieter_Vandroemme {
            get {
                object obj = ResourceManager.GetObject("Dieter_Vandroemme", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderOpen_16x16_72 {
            get {
                object obj = ResourceManager.GetObject("FolderOpen_16x16_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Glenn_Desmadryl {
            get {
                object obj = ResourceManager.GetObject("Glenn_Desmadryl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_16x16_Refresh {
            get {
                object obj = ResourceManager.GetObject("Icon_16x16_Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_16x16_Solution {
            get {
                object obj = ResourceManager.GetObject("Icon_16x16_Solution", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Icon_32x32_vApus {
            get {
                object obj = ResourceManager.GetObject("Icon_32x32_vApus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastColoredTextBox
        ///
        ///The GNU Lesser General Public License, version 3.0 (LGPL-3.0)
        ///This license is a set of additional permissions added to version 3 of the GNU General Public License.
        ///GNU LESSER GENERAL PUBLIC LICENSE
        ///Version 3, 29 June 2007
        ///
        ///Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        ///
        ///Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.
        ///
        ///This version of the GNU Lesser General Public License incorporates th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap linkedIn {
            get {
                object obj = ResourceManager.GetObject("linkedIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Liz_van_Dijk {
            get {
                object obj = ResourceManager.GetObject("Liz_van_Dijk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OK {
            get {
                object obj = ResourceManager.GetObject("OK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Philip_Dubois {
            get {
                object obj = ResourceManager.GetObject("Philip_Dubois", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecycleBin {
            get {
                object obj = ResourceManager.GetObject("RecycleBin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
